name: Deploy Azure Function (.NET 8)

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: fiap-contacts-get
  PROJECT_PATH: src/FIAP.Contacts.Get

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} -c Release --no-restore

    - name: Publish
      run: dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ./publish

    - name: Deploy para Azure
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        package: ./publish
